👷 configure googleplay ci cd

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -14,15 +14,35 @@ workflows:
                 CM_KEYSTORE_PASSWORD: Encrypted()
                 CM_KEY_PASSWORD: Encrypted()
                 CM_KEY_ALIAS: Encrypted()
+                REACT_APP_GOOGLE_PLAYSTORE_REVENUECAT_KEY: Encrypted()
+                PACKAGE_NAME: "com.bloggero"
             node: 16.14.0
         scripts:
             - yarn install
             - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$CM_BUILD_DIR/android/local.properties"
-            - |
-                chmod -R 777 $CM_BUILD_DIR
-                echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
-                # build Android
-                cd android
-                ./gradlew assembleRelease
+            - name: Build Android release
+              script: | 
+                LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name '$PACKAGE_NAME')
+                if [ -z LATEST_BUILD_NUMBER ]; then
+                # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
+                    UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+                else
+                    UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+                fi
+                cd android && ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
+            
+            
         artifacts:
             - android/app/build/outputs/**/*.apk
+
+        publishing:
+            email:
+                recipients:
+                    - onaelmangabo@gmail.com
+                notify:
+                  success: true     # To not receive a notification when a build succeeds
+                  failure: false    # To not receive a notification when a build fails
+            google_play:
+              credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
+              track: internal
+              submit_as_draft: true
